
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyxskemtifnblxijufvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5eHNrZW10aWZuYmx4aWp1ZnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NTI0NzYsImV4cCI6MjA1NzQyODQ3Nn0.AkWJm_bomcPZzfUdNfX2UGMmH1cQNrjZg2K7IAMBpkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
